#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kdegraphics-thumbnailers
Version  : 18.08.0
Release  : 1
URL      : https://download.kde.org/stable/applications/18.08.0/src/kdegraphics-thumbnailers-18.08.0.tar.xz
Source0  : https://download.kde.org/stable/applications/18.08.0/src/kdegraphics-thumbnailers-18.08.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0
Requires: kdegraphics-thumbnailers-lib
Requires: kdegraphics-thumbnailers-license
Requires: kdegraphics-thumbnailers-data
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : qtbase-dev qtbase-extras mesa-dev

%description
No detailed description available

%package data
Summary: data components for the kdegraphics-thumbnailers package.
Group: Data

%description data
data components for the kdegraphics-thumbnailers package.


%package lib
Summary: lib components for the kdegraphics-thumbnailers package.
Group: Libraries
Requires: kdegraphics-thumbnailers-data
Requires: kdegraphics-thumbnailers-license

%description lib
lib components for the kdegraphics-thumbnailers package.


%package license
Summary: license components for the kdegraphics-thumbnailers package.
Group: Default

%description license
license components for the kdegraphics-thumbnailers package.


%prep
%setup -q -n kdegraphics-thumbnailers-18.08.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535196239
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1535196239
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/kdegraphics-thumbnailers
cp COPYING %{buildroot}/usr/share/doc/kdegraphics-thumbnailers/COPYING
cp COPYING.LIB %{buildroot}/usr/share/doc/kdegraphics-thumbnailers/COPYING.LIB
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/kservices5/gsthumbnail.desktop

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/gsthumbnail.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/kdegraphics-thumbnailers/COPYING
/usr/share/doc/kdegraphics-thumbnailers/COPYING.LIB
